# Generated by Django 2.1 on 2019-01-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0003_auto_20190117_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmodel',
            name='BillsF',
        ),
        migrations.AddField(
            model_name='testmodel',
            name='Files_xx_BillsF',
            field=models.TextField(default='', verbose_name='Files_xx_BillsF'),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='Files_xx_DataF',
            field=models.TextField(default='', max_length=100, verbose_name='Files_xx_DataF'),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='Files_xx_DetF',
            field=models.TextField(default='', max_length=100, verbose_name='Files_xx_DetF'),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='Files_xx_HistF',
            field=models.TextField(default='', max_length=100, verbose_name='Files_xx_HistF'),
        ),
    ]
