# Generated by Django 2.1 on 2019-01-18 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0005_auto_20190117_2233'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestModel',
            new_name='RealtyModel',
        ),
    ]
