# Generated by Django 2.1 on 2019-01-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0006_auto_20190118_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtymodel',
            name='NOTES',
            field=models.TextField(default='', verbose_name='NOTES'),
        ),
    ]
