# Generated by Django 2.1 on 2019-01-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0008_auto_20190118_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtymodel',
            name='Maps_xx_GIS',
            field=models.TextField(default='', verbose_name='Maps___GIS'),
        ),
        migrations.AddField(
            model_name='realtymodel',
            name='Maps_xx_Map',
            field=models.TextField(default='', verbose_name='Maps___Map'),
        ),
        migrations.AddField(
            model_name='realtymodel',
            name='NOTES',
            field=models.TextField(default='', verbose_name='NOTES'),
        ),
        migrations.AddField(
            model_name='realtymodel',
            name='Prop_Details_xx_Acres',
            field=models.TextField(default='', verbose_name='Prop_Details___Acres'),
        ),
        migrations.AddField(
            model_name='realtymodel',
            name='Subd',
            field=models.TextField(default='', verbose_name='Subd'),
        ),
    ]
