# Generated by Django 2.1 on 2019-01-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0002_auto_20190117_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='BillsF',
            field=models.TextField(default='', verbose_name='Files___BillsF'),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='Subd',
            field=models.TextField(default='', verbose_name='Subd'),
        ),
    ]
