# Generated by Django 2.1 on 2019-01-18 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0007_realtymodel_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtymodel',
            name='NOTES',
        ),
        migrations.RemoveField(
            model_name='realtymodel',
            name='Subd',
        ),
    ]
